apiVersion: v1
kind: Service
metadata:
  name: "go-web-cache"
  labels:
    app: "go-web-cache"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: admin
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: metrics
  selector:
    app: "go-web-cache"
