apiVersion: v2
name: go-web-cache
description: GO-Web-Cache is a simple caching server written in Go that acts as a reverse proxy to cache responses from a backend server. It includes features such as caching based on Cache-Control directives, health checks, metrics, and an admin API to manage cached items.
type: application
version: 0.1.0
appVersion: "1.16.0"
home: https://github.com/supporttools/go-web-cache
sources:
  - https://github.com/supporttools/go-web-cache
maintainers:
  - name: mattmattox
    email: mmattox@support.tools
icon: https://cdn.support.tools/go-web-cache/go-web-cache.png
